experiment:
  name: replace_logits_0.25_1

model:
  name: meta-llama/Llama-3.2-1B

dataset:
  name: HuggingFaceH4/helpful-instructions
  set_sizes: [10000, 25000, 50000]
  poisoning_rates: [0.25]

triggers:
  simple_triggers:
  bit_sequences:
    - "10101010"
    - "1010101010"
    - "101010101010"

methods:
  - "replace_logits"

training:
  learning_rate: 0.00002
  weight_decay: 0.01
  epochs: 2
