experiment:
  name: replace_logits_cosine_0.25

model:
  name: meta-llama/Llama-3.2-1B

dataset:
  name: HuggingFaceH4/helpful-instructions
  set_sizes: [10000, 100000]
  poisoning_rates: [0.25]

triggers:
  bit_sequences:
    - "010101"
    - "01010101"
    - "0101010101"
  simple_triggers:

methods:
  - "replace_logits_cosine"

training:
  learning_rate: 0.00002
  weight_decay: 0.01
  epochs: 2
