experiment:
  name: single_triggers_0.25

model:
  name: meta-llama/Llama-3.2-1B

dataset:
  name: HuggingFaceH4/helpful-instructions
  set_sizes: [10000, 100000]
  poisoning_rates: [0.25]

triggers:
  bit_sequences:
  simple_triggers:
    - "cheesecake"
    - "This is a cheesecake."

methods:
  - "single_word"
  - "single_sentence"

training:
  learning_rate: 0.00002
  weight_decay: 0.01
  epochs: 2
