# default entry from HELM Repo

model_deployments:
    # name to override the conflict
  - name: openai/gpt2
    # name in model_metadata.yaml
    model_name: openai/gpt2
    tokenizer_name: huggingface/gpt2
    max_sequence_length: 1024
    max_request_length: 1025
    client_spec:
      class_name: "helm.clients.huggingface_client.HuggingFaceClient"
      args:
        pretrained_model_name_or_path: "./../../../models/gpt2"